services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqHelpdeskBot
    ports:
      - "5672:5672"
      - "15672:15672"

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqubeHelpdeskBot
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
      - sonar.jdbc.username=sonarqube
      - sonar.jdbc.password=sonar
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresHelpdeskBot
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: